server:
  port: 3000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orquestrador: orquestrador
      notificacao-sucesso: notificacao-sucesso
      proposta-vaga: proposta-vaga
    consumer:
      group-id: notificacao-group
      auto-offset-reset: latest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.use.type.headers: false
        spring.json.add.type.headers: false

logging:
  level:
    org.apache.kafka: INFO
