server:
  port: 3000

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      notificacao-sucesso:  notificacao-sucesso
      consultas: consultas
      historico-sucesso: historico-sucesso
      proposta-vaga: proposta-vaga
    consumer:
      group-id: agendamento-group
      auto-offset-reset: latest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.use.type.headers: false
        spring.json.add.type.headers: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://agendamento-db:5432/agendamentos}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org.apache.kafka: INFO
    org.hibernate: DEBUG

# URLs dos microserviços para validação
services:
  usuario:
    url: ${USUARIO_SERVICE_URL:http://usuario-service:3000}
  hospital:
    url: ${HOSPITAL_SERVICE_URL:http://hospital-service:3000}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

